### ISSUE TITLE
Manual entering of challenge code

### ISSUE THREAD

**Issue by mrkatz** [pgrimaud/instagram-user-feed#190]
**Is your feature request related to a problem? Please describe.**
Is it possible to manually enter the checkpoint Challenge code rather then trying to access it via IMAP

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by paulhennell** [comment]
I would also like a way to do this rather than relying on the Imap setup. 

It looks like the main code is in `Instagram/Auth/Login.php` `checkpointChallenge()`, but that's a private function that exits if you don't have an ImapClient.

If there was a way to setup and then trigger `$challenge->sendSecurityCode($challengeContent);` followed by a way to submit a user provided `$code` to `$challenge->submitSecurityCode($challengeContent, $code)` you could make a 'link account' page that triggers the email and then manually submit the code you receive.

Is this worth exploring or does the current setup require the code to be part of the same process or something as the original request (making a submission somewhat harder to implement userside vs the automatic imap system).
