### ISSUE TITLE
Instagram does not accept login from server

### ISSUE THREAD

**Issue by bytehead** [pgrimaud/instagram-user-feed#91]
```
 Unknown error (Client error: `POST https://www.instagram.com/accounts/login/ajax/` resulted in a `400 Bad Request` response:             
  {"message": "checkpoint_required", "checkpoint_url": "/challenge/1476111775/cWbS154z0k/", "lock": false, "status": "fail (truncated...)  
  ). Please report it with a GitHub issue.
```

If I then open the link (`checkpoint_url`) Instagram asks me follwing:

```
We have detected a suspicious log-in attempt
Web | Jun 20, 04:07AM
Basel, Switzerland

Let us know if you did this to protect your account.
```

Any idea to circumvent this?

**Comment by bytehead** [comment]
I've just seen #69. So closing :-)

**Comment by pgrimaud** [comment]
Related to https://github.com/pgrimaud/instagram-user-feed/issues/69

I had a serious accident 2 weeks ago. But fews days before I worked on it.
I'm stuck at the hospital for weeks, and I recovered my computer yesterday. So I will probably work on it on the next days, but slowly because my right arm is broken haha.

**Comment by bytehead** [comment]
I've read about it! No stress attached, I've seen your feature branch, interesting approach! 😎 May I find some time to test. Get well soon! 🍀
